### ISSUE TITLE
Submit to JS Frameworks benchmarks

### ISSUE THREAD

**Issue by brodybits** [sokra/rawact#6]
<https://github.com/krausest/js-framework-benchmark>

**Comment by sokra** [comment]
I will do so. Here are my local results so far:

![image](https://user-images.githubusercontent.com/1365881/48424842-d8360e80-e763-11e8-8a7e-7afd91a50031.png)
![image](https://user-images.githubusercontent.com/1365881/48424871-e84dee00-e763-11e8-92c8-9ecf87067053.png)
![image](https://user-images.githubusercontent.com/1365881/48424887-f439b000-e763-11e8-9430-7eb1d0df0c83.png)
![image](https://user-images.githubusercontent.com/1365881/48424900-fd2a8180-e763-11e8-81d6-5b425a1732d9.png)

**Comment by sokra** [comment]
https://github.com/krausest/js-framework-benchmark/pull/486

**Comment by brodybits** [comment]
:tada: Looks like you *mostly* beat standard React (with what looks like a minor exception in "select rows").

**Comment by sokra** [comment]
yeah, seams like `shouldComponentUpdate` is more efficient than `useMemo`. (select rows)

replace all rows is so much faster, because rawact recycles DOM nodes, while react creates new ones and throws away old. Maybe we remove this recycling to archive react compat (or behind a 
flag)

swap rows seem to be a problem in react.

But wait for the real benchmark, my local results have a low precision, because I didn't do a lot of runs (high std-dev)

**Comment by ryansolid** [comment]
Haven't had a chance to review your implementation but the "Replace All" for keyed having almost the same performance for non-keyed seems off. It could just be the reolution but to save some time in submission you can check. Keyed shouldn't be recycling DOM nodes. For example if you add 1000 rows and open up the debugger and manually add the 'danger' class to tr at row 3. Deleting row 2 should move that element up and now the 2nd row should be selected.

One can check whether an implementation is keyed or non-keyed via npm run isKeyed in the webdriver-ts directory. You can limit which frameworks to check in the same way as the webdriver test runner like e.g. npm run isKeyed -- --framework rawact. The program will report an error if a benchmark implementation is incorrectly classified.

**Comment by sokra** [comment]
Frameworks that will be checked rawact-v0.4.0-keyed rawact-v0.4.0-non-keyed

rawact-v0.4.0-keyed is keyed for 'run benchmark' and keyed for 'remove row benchmark' keyed for 'swap rows benchmark' . It'll appear as keyed in the results

rawact-v0.4.0-non-keyed is non-keyed for 'run benchmark' and non-keyed for 'remove row benchmark' non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results

**Comment by sokra** [comment]
If that isn't allowed the `isKeyed` detection should be updated.

Recycling happens only if you delete a row and add a row at the same time. Instead of removing the deleted row and creating a new one, rawact updates the DOM of the deleted row to match the new row and move it to the correct position. When manually adding classes or other DOM changes it will probably break, but in normal usage you won't see a difference.

**Comment by sokra** [comment]
The recycling was removed, the results are now live
